<?php
    define("DB_HOST","localhost");
    define("DB_USER","root");
    define("DB_PASS","");
    define("DB_NAME","qlkvc-nhom4-web");
    define("WEB_ROOT","http://localhost:440/QLKVC-MVC/");
    define("COOKIE_NAME","siteAuth");
    define("COOKIE_TIME",(3600*24*30));
?>